import type { Metadata } from "next";
import "../../../app/globals.css";
import "../../components/Common/common.scss";




export const metadata: Metadata = {
   title: "DesertBoard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased overflow-x-hidden`}
      >
        
          {children}
          
      </body>
    </html>
  );
}
