export type Sustainability = {
    sustainability:{
        bannerImage:string;
        description:string;
        goals:{
            description:string;
            heading:string;
            goals:{
                description:string;
                heading:string;
                image:string;
                logo:string;
                _id:string;
            }[]
        }
        heading:string;
        image:string;
        pageDescription:string;
        pageHeading:string;
        partners:{
            description:string;
            heading:string;
            partners:{
                description:string;
                title:string;
                _id:string;
            }[]
        }
        roles:{
            description:string;
            image:string;
            logo:string;
            title:string;
            _id:string;
        }[]
        vision:{
            description:string;
            image:string;
            region:string;
            title:string;
            _id:string;
        }[]
        _id:string;
    }
}