export const newsEvents = [
  {
    id: 1,
    type: "news",
    imageSrc: "/assets/images/News/news1.jpg",
    date: "January 9, 2025",
    title: "DesertBoard® at Al Ain Dates Festival 2025: Honouring Emirati Heritage with Sustainable Building Solutions.",
    desc: "DesertBoard® proudly participated in the Al Ain Dates Festival 2025, held from January 3rd to 8th under the esteemed patronage of His Highness Sheikh Mansour bin Zayed Al Nahyan. Organized by the Abu Dhabi Heritage Authority at Wahat Hili, Al-Ain, the festival celebrated the historical significance of the palm tree as a symbol of Emirati heritage while promoting awareness of UAE traditions and cultural practices.",
    categories: ["Company News", "Sustainability"],
    readMoreLink: "#",
  },
  {
    id: 2,
    type: "news",
    imageSrc: "/assets/images/News/news2.jpg",
    date: "November 30, 2024",
    title: "DesertBoard® Stands Out at Big 5 Global with Its Unique Lineup of Sustainable Solutions",
    desc: "DesertBoard® proudly participated in the Al Ain Dates Festival 2025, held from January 3rd to 8th under the esteemed patronage of His Highness Sheikh Mansour bin Zayed Al Nahyan. Organized by the Abu Dhabi Heritage Authority at Wahat Hili, Al-Ain, the festival celebrated the historical significance of the palm tree as a symbol of Emirati heritage while promoting awareness of UAE traditions and cultural practices.",
    categories: ["Company News", "Sustainability"],
    readMoreLink: "#",
  },
  {
    id: 3,
    type: "news",
    imageSrc: "/assets/images/News/news3.jpg",
    date: "November 26, 2024",
    title: "Building a Sustainable Hospitality Industry: Solutions & Best Practices",
    desc: "DesertBoard® proudly participated in the Al Ain Dates Festival 2025, held from January 3rd to 8th under the esteemed patronage of His Highness Sheikh Mansour bin Zayed Al Nahyan. Organized by the Abu Dhabi Heritage Authority at Wahat Hili, Al-Ain, the festival celebrated the historical significance of the palm tree as a symbol of Emirati heritage while promoting awareness of UAE traditions and cultural practices.",
    categories: ["Company News", "Sustainability"],
    readMoreLink: "#",
  },
  {
    id: 4,
    type: "news",
    imageSrc: "/assets/images/News/p4.png",
    date: "November 4, 2024",
    title: "DesertBoard’s PSB® reduces Dubai Design Week’s carbon footprint by over 12 ton",
    desc: "DesertBoard® proudly participated in the Al Ain Dates Festival 2025, held from January 3rd to 8th under the esteemed patronage of His Highness Sheikh Mansour bin Zayed Al Nahyan. Organized by the Abu Dhabi Heritage Authority at Wahat Hili, Al-Ain, the festival celebrated the historical significance of the palm tree as a symbol of Emirati heritage while promoting awareness of UAE traditions and cultural practices.",
    categories: ["Company News"],
    readMoreLink: "#",
  },
  {
    id: 5,
    type: "news",
    imageSrc: "/assets/images/News/p5.png",
    date: "September 6, 2024",
    title: "DesertBoard® showcases the region’s most sustainable building material at Saudi Wood Expo",
    desc: "DesertBoard® proudly participated in the Al Ain Dates Festival 2025, held from January 3rd to 8th under the esteemed patronage of His Highness Sheikh Mansour bin Zayed Al Nahyan. Organized by the Abu Dhabi Heritage Authority at Wahat Hili, Al-Ain, the festival celebrated the historical significance of the palm tree as a symbol of Emirati heritage while promoting awareness of UAE traditions and cultural practices.",
    categories: ["Company News", "Sustainability"],
    readMoreLink: "#",
  },
  {
    id: 6,
    type: "news",
    imageSrc: "/assets/images/News/p6.png",
    date: "June 28, 2024",
    title: "Factors To Consider When Choosing the Right Shuttering Board",
    desc: "DesertBoard® proudly participated in the Al Ain Dates Festival 2025, held from January 3rd to 8th under the esteemed patronage of His Highness Sheikh Mansour bin Zayed Al Nahyan. Organized by the Abu Dhabi Heritage Authority at Wahat Hili, Al-Ain, the festival celebrated the historical significance of the palm tree as a symbol of Emirati heritage while promoting awareness of UAE traditions and cultural practices.",
    categories: ["Product Specific"],
    readMoreLink: "#",
  },
  {
    id: 7,
    type: "expertise",
    imageSrc: "/assets/images/News/p7.png",
    date: "February 27, 2024",
    title: "Dubai WoodShow: Desert Board To Highlight Solutions As Mass Timber Trend Rises",
    desc: "DesertBoard® proudly participated in the Al Ain Dates Festival 2025, held from January 3rd to 8th under the esteemed patronage of His Highness Sheikh Mansour bin Zayed Al Nahyan. Organized by the Abu Dhabi Heritage Authority at Wahat Hili, Al-Ain, the festival celebrated the historical significance of the palm tree as a symbol of Emirati heritage while promoting awareness of UAE traditions and cultural practices.",
    categories: ["Company News", "Sustainability"],
    readMoreLink: "#",
  },
  {
    id: 8,
    type: "expertise",
    imageSrc: "/assets/images/News/p8.png",
    date: "February 13, 2024",
    title: "Defining UAE’s Approach Towards Eco-friendly Building Materials",
    desc: "DesertBoard® proudly participated in the Al Ain Dates Festival 2025, held from January 3rd to 8th under the esteemed patronage of His Highness Sheikh Mansour bin Zayed Al Nahyan. Organized by the Abu Dhabi Heritage Authority at Wahat Hili, Al-Ain, the festival celebrated the historical significance of the palm tree as a symbol of Emirati heritage while promoting awareness of UAE traditions and cultural practices.",
    categories: ["Product Specific", "Sustainability"],
    readMoreLink: "#",
  },
  {
    id: 9,
    type: "expertise",
    imageSrc: "/assets/images/News/p9.png",
    date: "November 8, 2023",
    title: "Circular Construction: Palm Fronds to Palm Strand Board",
    desc: "DesertBoard® proudly participated in the Al Ain Dates Festival 2025, held from January 3rd to 8th under the esteemed patronage of His Highness Sheikh Mansour bin Zayed Al Nahyan. Organized by the Abu Dhabi Heritage Authority at Wahat Hili, Al-Ain, the festival celebrated the historical significance of the palm tree as a symbol of Emirati heritage while promoting awareness of UAE traditions and cultural practices.",
    categories: ["Sustainability"],
    readMoreLink: "#",
  },
];

export const linkedInSliderData = [
  {
    id: 1,
    timePosted:"4 hours ago",
    desc:"1 DesertBoard is proud to participate in the Al Ain Dates Festival, held under the",
    imageSrc: "/assets/images/linkedin/post1.jpg",
    likes:"14"
  },
  {
    id: 2,
    timePosted:"4 hours ago",
    desc:"2 DesertBoard is proud to participate in the Al Ain Dates Festival, held under the",
    imageSrc: "/assets/images/linkedin/post2.jpg",
    likes:"14"
  },
  {
    id: 3,
    timePosted:"4 hours ago",
    desc:"3 DesertBoard is proud to participate in the Al Ain Dates Festival, held under the",
    imageSrc: "/assets/images/linkedin/post3.jpg",
    likes:"14"
  },
  {
    id: 4,
    timePosted:"4 hours ago",
    desc:"4 DesertBoard is proud to participate in the Al Ain Dates Festival, held under the",
    imageSrc: "/assets/images/linkedin/post4.jpg",
    likes:"14"
  },
  {
    id: 5,
    timePosted:"4 days ago",
    desc:"5 DesertBoard is proud to participate in the Al Ain Dates Festival, held under the",
    imageSrc: "/assets/images/linkedin/post5.jpg",
    likes:"14"
  },

];
