import type { Metadata } from "next";
import "./globals.css";
import "./components/Common/common.scss";
import Header from "./components/Header";
import Footer from "./components/Common/footer";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` antialiased overflow-x-hidden`}
      >
        <Header/>
          {children}
          <Footer/>
      </body>
    </html>
  );
}
