import type { Metadata } from "next";
import "../../app/globals.css";
import "../../app/components/Common/common.scss";
import Footer from "../components/Common/footer";
import Header from "../components/Headernew";



export const metadata: Metadata = {
   title: "DesertBoard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased overflow-x-hidden`}
      >
        <Header/>
          {children}
          <Footer/>
      </body>
    </html>
  );
}
